name: mxnet_p36
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.1
  - bleach=2.0.0
  - bzip2=1.0.6
  - ca-certificates=2018.4.16
  - cairo=1.14.6
  - certifi=2018.4.16
  - dbus=1.10.22
  - decorator=4.1.2
  - entrypoints=0.2.3
  - ffmpeg=3.2.4
  - fontconfig=2.12.1
  - freetype=2.7
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.51.4
  - gmp=6.1.2
  - graphviz=2.38.0
  - gst-plugins-base=1.8.0
  - gstreamer=1.8.0
  - harfbuzz=1.3.4
  - hdf5=1.10.1
  - html5lib=1.0.1
  - ipdb=0.11
  - ipykernel=4.8.2
  - ipython=6.2.1
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jedi=0.11.1
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter_client=5.2.2
  - jupyter_core=4.4.0
  - libiconv=1.15
  - libpng=1.6.28
  - libsodium=1.0.15
  - libtiff=4.0.7
  - libwebp=0.5.2
  - markupsafe=1.0
  - mistune=0.8.3
  - nb_conda=2.2.1
  - nb_conda_kernels=2.1.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.4.0
  - numpy=1.14.1
  - openblas=0.2.20
  - opencv=3.3.0
  - openssl=1.0.2o
  - pandoc=2.1.1
  - pandocfilters=1.4.1
  - pango=1.40.3
  - parso=0.1.1
  - pexpect=4.4.0
  - pickleshare=0.7.4
  - prompt_toolkit=1.0.15
  - protobuf=3.5.0
  - ptyprocess=0.5.2
  - pygments=2.2.0
  - python-dateutil=2.6.1
  - pyzmq=17.0.0
  - qt=5.6.2
  - scikit-learn=0.19.1
  - scipy=1.0.1
  - send2trash=1.5.0
  - simplegeneric=0.8.1
  - six=1.11.0
  - terminado=0.8.1
  - testpath=0.3.1
  - tornado=4.5.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5
  - x264=20131217
  - yappi=0.98
  - zeromq=4.2.3
  - asn1crypto=0.24.0
  - attrs=18.1.0
  - autovizwidget=0.12.5
  - bokeh=0.12.14
  - cffi=1.11.4
  - chardet=3.0.4
  - coverage=4.5.1
  - cryptography=2.1.4
  - expat=2.2.5
  - graphite2=1.3.10
  - hdijupyterutils=0.12.5
  - hypothesis=3.56.0
  - icu=58.2
  - idna=2.6
  - intel-openmp=2018.0.0
  - ipywidgets=7.1.2
  - joblib=0.11
  - jpeg=9b
  - krb5=1.14.2
  - libedit=3.1
  - libffi=3.2.1
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.2.0
  - libstdcxx-ng=7.2.0
  - libtool=2.4.6
  - libxcb=1.12
  - libxml2=2.9.7
  - line_profiler=2.0
  - mkl=2018.0.1
  - ncurses=6.0
  - networkx=2.1
  - openjdk=8.0.121
  - packaging=16.8
  - pandas=0.22.0
  - pcre=8.41
  - pip=9.0.1
  - pixman=0.34.0
  - plotly=2.4.0
  - pycparser=2.18
  - pykerberos=1.1.14
  - pyopenssl=17.5.0
  - pyparsing=2.2.0
  - pysocks=1.6.7
  - python=3.6.4
  - pytz=2018.3
  - pyyaml=3.12
  - readline=7.0
  - requests=2.18.4
  - requests-kerberos=0.11.0
  - setuptools=38.5.1
  - sparkmagic=0.12.5
  - sqlite=3.22.0
  - tk=8.6.7
  - tqdm=4.19.8
  - urllib3=1.22
  - wheel=0.30.0
  - widgetsnbextension=3.1.4
  - xz=5.2.3
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - boto3==1.5.34
    - botocore==1.8.48
    - click==6.7
    - cycler==0.10.0
    - docutils==0.14
    - editdistance==0.4
    - environment-kernels==1.1.1
    - flask==0.12.2
    - flask-cors==3.0.3
    - itsdangerous==0.24
    - jmespath==0.9.3
    - keras-mxnet==1.2.2
    - matplotlib==2.1.2
    - mxnet-cu90mkl==1.3.0b20180822
    - mxnet-model-server==0.1.5
    - pillow==5.0.0
    - psutil==5.4.3
    - psycopg2==2.7.4
    - py4j==0.10.4
    - pygal==2.4.0
    - pyspark==2.2.1
    - s3transfer==0.1.13
    - sqlalchemy==1.2.3
    - werkzeug==0.14.1

